name: Build Web App
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore Tutor-Testing-4.3.sln
 
    - name: Build App
      run: msbuild Tutor-Testing-4.3.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:PackageAsSingleFile=false
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: release
        path: bin\Release
      
